# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('data', models.TextField()),
                ('snippet', models.TextField(null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='reading.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='tags',
            field=models.ManyToManyField(to='reading.Tags'),
        ),
        migrations.AddField(
            model_name='read',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Write'),
        ),
    ]
