# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('data', models.CharField(max_length=4000)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.Read')),
            ],
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=4000)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='readwrite',
            name='write',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.Write'),
        ),
    ]
