# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='readwrite',
            name='read',
        ),
        migrations.RemoveField(
            model_name='readwrite',
            name='write',
        ),
        migrations.AddField(
            model_name='read',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Write'),
        ),
        migrations.DeleteModel(
            name='ReadWrite',
        ),
        migrations.AddField(
            model_name='read',
            name='tags',
            field=models.ManyToManyField(to='reading.Tags'),
        ),
        migrations.AddField(
            model_name='write',
            name='tags',
            field=models.ManyToManyField(to='reading.Tags'),
        ),
    ]
