# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_auto_20161104_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='read',
            name='write',
        ),
    ]
