# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_auto_20161104_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='tags',
            field=models.ManyToManyField(null=True, to='reading.Tags'),
        ),
        migrations.AddField(
            model_name='read',
            name='write',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.Write'),
        ),
    ]
