# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_auto_20161107_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='read',
            name='tags',
            field=models.ManyToManyField(to='reading.Tags'),
        ),
        migrations.AlterField(
            model_name='write',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
