# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_auto_20161109_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='data',
            field=models.TextField(),
        ),
    ]
