# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_auto_20161109_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='write',
            name='data',
            field=models.CharField(max_length=4000),
        ),
    ]
