









































































     #
     #
     #
     #
     # 'figure_align': 'htbp',
     # 'papersize': 'letterpaper',
     # 'pointsize': '10pt',
     # 'preamble': '',
     # Additional stuff for the LaTeX preamble.
     # Latex figure (float) alignment
     # The font size ('10pt', '11pt' or '12pt').
     # The paper size ('letterpaper' or 'a4paper').
     'Miscellaneous'),
     [author], 1)
     author, 'django-tutorial', 'One line description of project.',
     u'Dhruv Shah', 'manual'),
    'sphinx.ext.githubpages',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    (master_doc, 'django-tutorial', u'django-tutorial Documentation',
    (master_doc, 'django-tutorial', u'django-tutorial Documentation',
    (master_doc, 'django-tutorial.tex', u'django-tutorial Documentation',
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#  author, documentclass [howto, manual, or own class]).
#  dir menu entry, description, category)
# "<project> v<release> documentation" by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
# (source start file, name, description, authors, manual section).
# (source start file, target name, title,
# (source start file, target name, title, author,
# -*- coding: utf-8 -*-
# -- General configuration ------------------------------------------------
# -- Options for HTML output ----------------------------------------------
# -- Options for LaTeX output ---------------------------------------------
# -- Options for manual page output ---------------------------------------
# -- Options for Texinfo output -------------------------------------------
# .htaccess) here, relative to this directory. These files are copied
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# A dictionary with options for the search language support, empty by default.
# a list of builtin themes.
# A list of ignored prefixes for module index sorting.
# A shorter title for the navigation bar.  Default is the same as html_title.
# Add any extra paths that contain custom files (such as robots.txt or
# Add any paths that contain custom static files (such as style sheets) here,
# Add any paths that contain custom themes here, relative to this directory.
# Add any paths that contain templates here, relative to this directory.
# Add any Sphinx extension module names here, as strings. They can be
# add these directories to sys.path here. If the directory is relative to the
# add_function_parentheses = True
# add_module_names = True
# Additional templates that should be rendered to pages, maps page names to
# All configuration values have a default; values that are commented out
# autogenerated file.
# base URL from which the finished HTML is served.
# bottom, using the given strftime format.
# built documents.
# contain a <link> tag referring to it.  The value of this option must be the
# containing dir.
# Custom sidebar templates, maps document names to template names.
# default_role = None
# directly to the root of the documentation.
# directories to ignore when looking for source files.
# django-tutorial documentation build configuration file, created by
# documentation root, use os.path.abspath to make it absolute, like shown here.
# documentation.
# Documents to append as an appendix to all manuals.
# Documents to append as an appendix to all manuals.
# documents.
# Else, today_fmt is used as the format for a strftime call.
# Example configuration for intersphinx: refer to the Python standard library.
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# For "manual" documents, if this is true, then toplevel headings are parts,
# for a list of supported languages.
# further.  For a list of options available for each theme, see the
# General information about the project.
# Grouping the document tree into LaTeX files. List of tuples
# Grouping the document tree into Texinfo files. List of tuples
# How to display URL addresses: 'footnote', 'no', or 'inline'.
# html_additional_pages = {}
# html_domain_indices = True
# html_extra_path = []
# html_favicon = None
# html_file_suffix = None
# html_last_updated_fmt = None
# html_logo = None
# html_search_language = 'en'
# html_search_options = {'type': 'default'}
# html_search_scorer = 'scorer.js'
# html_short_title = None
# html_show_copyright = True
# html_show_sourcelink = True
# html_show_sphinx = True
# html_sidebars = {}
# html_split_index = False
# html_theme_options = {}
# html_theme_path = []
# html_title = u'django-tutorial v0.0.1'
# html_use_index = True
# html_use_opensearch = ''
# html_use_smartypants = True
# If extensions (or modules to document with autodoc) are in another directory,
# If false, no index is generated.
# If false, no module index is generated.
# If false, no module index is generated.
# If false, no module index is generated.
# If not None, a 'Last updated on:' timestamp is inserted at every page
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# If true, '()' will be appended to :func: etc. cross-reference text.
# If true, `todo` and `todoList` produce output, else they produce nothing.
# If true, an OpenSearch description file will be output, and all pages will
# If true, do not generate a @detailmenu in the "Top" node's menu.
# If true, keep warnings as "system message" paragraphs in the built documents.
# If true, links to the reST sources are added to the pages.
# If true, sectionauthor and moduleauthor directives will be shown in the
# If true, show page references after internal links.
# If true, show URL addresses after external links.
# If true, show URL addresses after external links.
# If true, SmartyPants will be used to convert quotes and dashes to
# If true, the current module name will be prepended to all description
# If true, the index is split into individual pages for each letter.
# If your documentation needs a minimal Sphinx version, state it here.
# implements a search results scorer. If empty, the default will be used.
# import os
# import sys
# It false, will not define \strong, \code,     itleref, \crossref ... but only
# keep_warnings = False
# Language to be used for generating the HTML full-text search index.
# latex_appendices = []
# latex_domain_indices = True
# latex_keep_old_macro_names = True
# latex_logo = None
# latex_show_pagerefs = False
# latex_show_urls = False
# latex_use_parts = False
# List of patterns, relative to source directory, that match files and
# man_show_urls = False
# modindex_common_prefix = []
# needs_sphinx = '1.0'
# non-false value, then it is used:
# not chapters.
# Note that not all possible configuration values are present in this
# of the sidebar.
# One entry per manual page. List of tuples
# ones.
# Output file base name for HTML help builder.
# output. They are ignored by default.
# packages.
# pixels large.
# relative to this directory. They are copied after the builtin static files,
# serve to show the default.
# show_authors = False
# so a file named "default.css" will overwrite the builtin "default.css".
# source_encoding = 'utf-8-sig'
# source_suffix = ['.rst', '.md']
# Sphinx supports the following languages:
# sphinx-quickstart on Fri Oct 21 12:02:31 2016.
# sys.path.insert(0, os.path.abspath('.'))
# template names.
# texinfo_appendices = []
# texinfo_domain_indices = True
# texinfo_no_detailmenu = False
# texinfo_show_urls = 'footnote'
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# The empty string is equivalent to '%b %d, %Y'.
# The encoding of source files.
# The full version, including alpha/beta/rc tags.
# The language for content autogenerated by Sphinx. Refer to documentation
# The master toctree document.
# The name for this set of Sphinx documents.
# The name of a javascript file (relative to the configuration directory) that
# The name of an image file (relative to this directory) to place at the top
# The name of an image file (relative to this directory) to place at the top of
# The name of an image file (relative to this directory) to use as a favicon of
# The name of the Pygments (syntax highlighting) style to use.
# The reST default role (used for this markup: `text`) to use for all
# The short X.Y version.
# The suffix(es) of source filenames.
# The theme to use for HTML and HTML Help pages.  See the documentation for
# the title page.
# The version info for the project you're documenting, acts as replacement for
# Theme options are theme-specific and customize the look and feel of a theme
# There are two options for replacing |today|: either, you set today to some
# This file is execfile()d with the current directory set to its
# This is also used if you do content translation via gettext catalogs.
# This is the file name suffix for HTML files (e.g. ".xhtml").
# This patterns also effect to html_static_path and html_extra_path
# today = ''
# today_fmt = '%B %d, %Y'
# typographically correct entities.
# unit titles (such as .. function::).
# Usually you set "language" from the command line for these cases.
# You can specify multiple suffix as a list of string:
# |version| and |release|, also used in various other places throughout the
]
]
]
]
author = u'Dhruv Shah'
copyright = u'2016, Dhruv Shah'
exclude_patterns = []
extensions = [
html_static_path = ['_static']
html_theme = 'alabaster'
htmlhelp_basename = 'django-tutorialdoc'
intersphinx_mapping = {'https://docs.python.org/': None}
language = None
latex_documents = [
latex_elements = {
man_pages = [
master_doc = 'index'
project = u'django-tutorial'
pygments_style = 'sphinx'
release = u'0.0.1'
source_suffix = '.rst'
templates_path = ['_templates']
texinfo_documents = [
todo_include_todos = False
version = u'0.0.1'
}